import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Generate a Mock Time Series</h1>
      <div className={styles.input}> Samplerate: 
        <input type="number"/>
      </div>
      <div className={styles.input}> Duration: 
        <input type="number"/>
      </div>
      <div className={styles.button}> 
        <button>Generate</button>
      </div>
      <div className={styles.button}> 
        <button>Delete</button>
      </div>
      <div className={styles.container}>
      <table>
  <tr>
    <th>Value 1</th>
    <th>Value 2</th>
  </tr>
  <tr>
    <td>-1222.12</td>
    <td>1.27364</td>
  </tr>
</table>
      </div>
    </div>
  )
}
